.TH QSHELL 1 "AUGUST 2013" GNU "qshell User Manuals"

.SH NAME
qshell - a simple shell

.SH SYNOPSIS
.B /path/to/qshell
.RB [file]

.SH DESCRIPTION
qshell is a command interpreter that executes commands read from the
standard input. qshell has three built in, native, commands and
incorporates functions from other shells.

.SH OPTIONS
qshell does not take any options. However, a filename can be supplied.

.SH ARGUMENTS
If an argument is provided after the qshell command, it is assumed to
be a file name containing shell commands. qshell will read these commands,
without printing the prompt to the user.

.SH EXIT STATUS
qshell, itself, will exit with a a status of 0 on success.
On any failure or error, it will exit with a status of 1.

The
.BR waitpid(2)
function returns the exit status of executed commands.

.SH ENVIRONMENT
qshell uses the following environment variables.
.TP
.I PATH
The exec function uses path to look for commands.
.TP
.I HOME
The built-in qhsell command, cd, uses HOME to change working directory.

.SH FILES
.TP
.I qshell.tar.gzip
The gunzipped tarball containing all the qshell files.
.TP
.I makefile
Makefile to build qshell
.TP
.I qshell
The qshell executable
.TP
.I qshell.1
The qshell man-page
.TP
.I /dev/null
Used for standard input redirect in background commands.

.SH NOTES
Functionality and behaviour was modeled of the bash shell if the assignment
specifications did not provide a full description or outline.

Stdout for background tasks is printed after the task has finished and
before the next prompt is printed.

On exit all background tasks are stopped and cleaned up.

.SH BUGS
.TP
.I "Standard Error Redirection"
Standard Error is never redirected. This causes background processes to
output error messages directly onto the terminal. 

.SH EXAMPLE
To run a file, called filetest, that contains shell commands. If both the
qshell executable and filetes are in the current directory.
The command would be: ./qshell filetest

.SH SEE ALSO
.BR bash(1),
.BR waitpid(2)

.SH AUTHOR
Aaron Hayes (42338468) <aaron.hayes@uqconnect.edu.au>